added the program of brackets as mentioned in the issue #21
PEC-CSS/Open-Source pull request #23
Opened 2021-09-16 15:55 UTC by VedRatan

added the program in DSA directory

2021-09-16 16:05 UTC, Gauravsharma-20 commented
Add the program in Good-First-Issues folder and name the file Generate_Balanced_Parentheses.cpp

2021-09-16 16:31 UTC, Gauravsharma-20 approved these changes

2021-09-16 16:31 UTC, VedRatan commented
done the job as specified sir

2021-09-16 16:54 UTC, ultimatecoder2 reviewed
Please add a case for n=0 too. Your program will go for infinite recursive calls. 
Rest seems fine.

2021-09-16 16:56 UTC, VedRatan commented
> Please add a case for n=0 too. Your program will go for infinite recursive calls.
> Rest seems fine.

ohh ya got it thanks a lot, updating soon.

2021-09-16 17:01 UTC, VedRatan commented
handled the egde case sir

2021-09-16 17:07 UTC, ultimatecoder2 approved these changes

2021-09-17 03:45 UTC, Gauravsharma-20 commented
@VedRatan please remove the two stack file we are just accepting 1 good first issue per user for now, we'll add more issues in the coming days.

2021-09-17 04:48 UTC, Gauravsharma-20 requested changes

2021-09-17 04:48 UTC, Gauravsharma-20 commented on Good-First-Issues/two_stack_using_single_array.cpp
> +{
please remove this file

2021-09-17 05:35 UTC, VedRatan commented on Good-First-Issues/two_stack_using_single_array.cpp
> +{
okk sir

2021-09-17 05:40 UTC, Gauravsharma-20 approved these changes

2021-09-17 15:57 UTC, Vibhu1710 approved these changes

2021-09-17 17:28 UTC, merged